language: cpp
python:
- '3.4'
git:
  depth: 1000
os:
- linux
- osx
sudo: required
dist: trusty
osx_image: xcode8.3
notifications:
  slack:
    rooms:
      secure: g0pn+4g7d+2KXW88mL4zgCU0CjjpXcYPsdqM3y+M8xllo0bM201uhe+JBQi9AmXynLCV5qDoK3N5Fu1UoEW9zdKoi6c6HzCgb8vFZ1BBeNGfcGc/EkxgyimubJ66EfM7EuU8TAc76N/OO3YTagnV39/C1NoMLzblgbS/4kyy3Ay5237qo9asDhrgt9YaRuTjQ8M4VYG+0hsjtZpIBF2ZhsCHw1i2YPHVd4EYdfj8JxKEueo+FSU3uxgD+5HCIhCThD4QqVWWlbR7cMkbmE8gWnJLqVOCqzH3CG1zv4ASGjJbH4NUWFf8zXfhiGGCoXyMX/DOtYbMwD5poNj0k5UG6L0AyO6L2VoWh5qTsrrg4hZIl5VILUOqcNgVibIOPV3B39OTZnMEVDs3gtUP+v5yCfYF7uCc/ziNmaj1nzMHsV5fhC+qZkuaWKVc0zc6BdVMt6OjMqf2kiJO3bCmw3BKs4WmvkACDrDQzMOFiq53OWQkP300sdsmFislUBQK4olDhBVWofPex7vHIxu1y0E9SndgT6b7/JzIJvzWQLr/adUny9yS05G13Bv+3p7AbIuIOzGwDLkrCSVVTDParujX3dgCbqr+7C8fdTic2jDInaLCR5BpON4Ve6BNwk+81HdT9DegtGpJsfDN97nr6tWBMA0WCJkQ+pIHuAo8Ry4s24w=
    on_success: always
    on_failure: always
    on_start: always
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/ae6f3aa6248f45c9cbff
    on_success: always
    on_failure: always
    on_start: always
before_install:
- chmod +x ci/download.sh
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install openssl; brew
  install python3; mkdir -p /usr/local/lib; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install python3; nvm
  install v6.0.0; fi
install:
- pushd ci
- "./download.sh"
- popd
before_script:
- export PATH=~/.local/bin:$PATH
script:
- ulimit -n 4096
- pwsh -File ci/init.ps1
