language: cpp
python:
- '3.4'
git:
  depth: 1000
os:
- linux
- osx
sudo: required
dist: trusty
osx_image: xcode8.3
notifications:
  slack:
    rooms:
      secure: g0pn+4g7d+2KXW88mL4zgCU0CjjpXcYPsdqM3y+M8xllo0bM201uhe+JBQi9AmXynLCV5qDoK3N5Fu1UoEW9zdKoi6c6HzCgb8vFZ1BBeNGfcGc/EkxgyimubJ66EfM7EuU8TAc76N/OO3YTagnV39/C1NoMLzblgbS/4kyy3Ay5237qo9asDhrgt9YaRuTjQ8M4VYG+0hsjtZpIBF2ZhsCHw1i2YPHVd4EYdfj8JxKEueo+FSU3uxgD+5HCIhCThD4QqVWWlbR7cMkbmE8gWnJLqVOCqzH3CG1zv4ASGjJbH4NUWFf8zXfhiGGCoXyMX/DOtYbMwD5poNj0k5UG6L0AyO6L2VoWh5qTsrrg4hZIl5VILUOqcNgVibIOPV3B39OTZnMEVDs3gtUP+v5yCfYF7uCc/ziNmaj1nzMHsV5fhC+qZkuaWKVc0zc6BdVMt6OjMqf2kiJO3bCmw3BKs4WmvkACDrDQzMOFiq53OWQkP300sdsmFislUBQK4olDhBVWofPex7vHIxu1y0E9SndgT6b7/JzIJvzWQLr/adUny9yS05G13Bv+3p7AbIuIOzGwDLkrCSVVTDParujX3dgCbqr+7C8fdTic2jDInaLCR5BpON4Ve6BNwk+81HdT9DegtGpJsfDN97nr6tWBMA0WCJkQ+pIHuAo8Ry4s24w=
    on_success: always
    on_failure: always
    on_start: always
  webhooks:
    urls:
      secure: loefE31kEeRlWkpGFfK+YpSAN4pRKaEq+n4u6xKNRKMCUED8oKaMA65SjARLPj4DHwpSIM0l5+8+z3V4c22cE7QhjDYXEhb1BHJiCc8T0ysWOZYOHe95ncWUKkn0QQOddKc5ayAt3qy5+rm/DFGXDi9hbSyCip9HYAn4gepH8b4hnBWpDoEpaTPNnn+6nUt9TTGC4iMn2S+NZ/p6t4mm1ZtIjq1v3yzRDMY6oq1/eJUzJ1078XFWAL5tUkRetrT5szHvpK84YPMo9h2hFw6N1yPvw/ZQOXwPmtHhhaZA7h0yY/XY9CvUjQFB125BK4gjpIsqklR6kFm+8iy/XB53tH5Gcy0e4fIuYa102JZXAZ5sqsLsewELH26sXR1vY1TGALkWHyvypSbeZtUzn8XtVuzyK2+P0b8tAKC4hHlJZg13DgQME+kzR1fw8KXOiCdv9tPKesr3DGb5YitZ5ESm/jHWxWO1ciqsKUUWLPR/J+iknTeZDxfJy+jELmo7msgedq1OTuLr8GACksKyoJAGNWSJQeLFFOJs2yMcwcJ8m12RowqoR/dJcPWWKqEVLEKUvNDecLMV2KObp/nASX++sSItz3eBnlJJCIUH3vC16Zwu7Y++7NoN64JfT7p/Ddk5kkJZYDnKAyK90wYqONoa/2lOPSjNj/JBw8/iulQn6yI=
    on_success: always
    on_failure: always
    on_start: always
before_install:
- chmod +x ci/download.sh
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install openssl; brew
  install python3; mkdir -p /usr/local/lib; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install python3; nvm
  install v6.0.0; fi
install:
- pushd ci
- "./download.sh"
- popd
before_script:
- export PATH=~/.local/bin:$PATH
script:
- ulimit -n 4096
- pwsh -File ci/init.ps1
