clone_folder: C:\projects\PSGSuite

image: Visual Studio 2017

environment:
  NuGetApiKey:
    secure: Ocp1ATd6eZ0eY9+LfZ9Stp9/J1B5eFdBPMdaTRWVa4xh6/NV45ZBYtU5+eemrTWt

skip_commits:
  message: /updated readme.*|update readme.*s|\[skip ci\]|\[ci skip\]/

only_commits:
  message: /!deploy|!build|!ci|\[ci\]/

build: false

test_script:
  - pwsh: . .\ci\init.ps1
  - ps: . .\ci\init.ps1