resources:
  repositories:
    - repository: templates
      type: github
      name: SCRT-HQ/AzurePipelineTemplates
      endpoint: Github

variables:
- name: PSGSuiteConfigJson
- group: deployment-vars

trigger:
  branches:
    include:
    - refs/heads/*

stages:
- template: BuildTestDeployModule/azure-pipelines.yml@templates
